timeout: '600s'

steps:
  # Step 1: Copy secret files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Fetch and write secrets
        gcloud secrets versions access latest --secret=auth-config-file > /workspace/src/auth_config.json
        gcloud secrets versions access latest --secret=react-env-file > /workspace/.env

  # Step 2: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Step 3: Build the application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Step 4: Deploy to Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

# Specify the output directory for build artifacts
artifacts:
  objects:
    location: '${_ARTIFACT_BUCKET_LOCATION}'
    paths: ['build/**']
